general:
  cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com/'
  cfOrg: '8d5dd292trial'
  cfSpace: 'dev'
  cfCredentialsId: 'stukkat01@gmail.com'
  cfServiceInstance: 'abapEnvironmentPipeline'
stages:
  Prepare System:
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'user@example.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: false
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1
  Clone Repositories:
    strategy: 'Clone'
    repositories: 'repositories.yml'
  ATC:
    # In order to be executed, the ATC stage needs at least one configuration entry
    # If the ATC stage should not be executed, delete the whole section
    execute: stage
  AUnit:
    # In order to be executed, the AUnit stage needs at least one configuration entry
    # If the AUnit stage should not be executed, delete the whole section
    execute: stage
  Post:
    cfDeleteServiceKeys: true
